### ISSUE TITLE
天才的想法

### ISSUE THREAD

**Issue by ljyloo** [manakanemu/ExHentaiReader#1]
给作者点个赞，感觉是个很有潜力的项目。这样就无需安装额外的app来看ex了，特别是iOS限制了xcode安装的app只能运行7天，现在我用自己编译的app每周都要刷新一次，特别繁琐

感觉可以改进的地方：
脚本运行直接打开ex或者eg，减少一步操作
懒加载，只加载滑动到的图片或者提前加载四五张图，不用一次全部加载
跳转到某一页
加载失败的图片可以选择加载原图或者换源

**Comment by manakanemu** [comment]
> 给作者点个赞，感觉是个很有潜力的项目。这样就无需安装额外的app来看ex了，特别是iOS限制了xcode安装的app只能运行7天，现在我用自己编译的app每周都要刷新一次，特别繁琐
> 
> 感觉可以改进的地方：
> 脚本运行直接打开ex或者eg，减少一步操作
> 懒加载，只加载滑动到的图片或者提前加载四五张图，不用一次全部加载
> 跳转到某一页
> 加载失败的图片可以选择加载原图或者换源

今天真的是晴天霹雳，e站没有了

**Comment by ljyloo** [comment]
今天它又活了

**Comment by ldm28** [comment]
挺好用的，pc端有没有类似的啊

**Comment by manakanemu** [comment]
> 挺好用的，pc端有没有类似的啊

可以写一个，不过pc都是宽屏，还是一行两三附图比较好

**Comment by manakanemu** [comment]
> 给作者点个赞，感觉是个很有潜力的项目。这样就无需安装额外的app来看ex了，特别是iOS限制了xcode安装的app只能运行7天，现在我用自己编译的app每周都要刷新一次，特别繁琐
> 
> 感觉可以改进的地方：
> 脚本运行直接打开ex或者eg，减少一步操作
> 懒加载，只加载滑动到的图片或者提前加载四五张图，不用一次全部加载
> 跳转到某一页
> 加载失败的图片可以选择加载原图或者换源

1、国内很多用户是用熊猫书签的，按照现在熊猫的代码逻辑，我怕我这个直接进ex反而会增加一部分人的操作复杂度。
2、懒加载我试了一下，效果一般。ex的图都是分布存储，大部分图都不从同一个服务器获得，其实一次加载全部和部分速度也差不了太多，反而有的时候遇到无聊的剧情需要快速跳过，而刚好遇到这个图片服务器访问的慢，反而会等半天。
3、自动换源最新版已经实现了。
