### ISSUE TITLE
您好请问怎么改标签

### ISSUE THREAD

**Issue by lhj5426** [manakanemu/ExHentaiReader#10]
最近发现在首页可以显示 一些中文 但是 有写没有 看着难受
然后我就想自己把自己常用的标签加上 但是遇到了问题 无论我是 FORK  或者是 自己新建 重新上传  
代码   修改过的 tag.json.js
 标签始终还是原来的 
 然后我试着在 仓库里删除 tag.json.js  我发现依然会显示 TAG 这下我明白了 无论怎么 弄生成的 代码 调用的都是您仓库里的
 tag.json.js
  我想问下载怎么能自由的更改 tag.json.js   
![image](https://user-images.githubusercontent.com/30548000/114657880-870b1a00-9d23-11eb-9949-180f38313e54.png)

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/114658333-33e59700-9d24-11eb-895e-066535e6fc84.png)
我用搜索关键字在代码里搜索 找到是这2个文件在调用 tag.json.js 可我不知道要怎么改才能自由的更改 TAG  能跟你请教下吗

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/114658528-8b840280-9d24-11eb-8910-bb4843230535.png)
![image](https://user-images.githubusercontent.com/30548000/114658552-92ab1080-9d24-11eb-8819-a338e6f0b508.png)
z我改成了这样 但是并不好使= =

**Comment by manakanemu** [comment]
为了避免每次调用脚本都重复请求字典，我做了字典本地化，字典在第一次请求以后会存储在本地window.localStorage里，同时会存储一个字典的版本号，也就是你在tag.json.js里看到的`"TAGDICVERSION":"1.3"`
在脚本中同样定义了一个字典号`currentTagDicVersion = 1.3` 如果本地存储的字典版本TAGDICVERSION大于等于currentTagDicVersion,是不会更新字典的。
如果你想用你自定义的字典，那么要么清除本地localStorage,要么把字典里的版本号和脚本里的版本号都改成大于1.3的相同的两个数。

**Comment by lhj5426** [comment]
> 为了避免每次调用脚本都重复请求字典，我做了字典本地化，字典在第一次请求以后会存储在本地window.localStorage里，同时会存储一个字典的版本号，也就是你在tag.json.js里看到的`"TAGDICVERSION":"1.3"`
> 在脚本中同样定义了一个字典号`currentTagDicVersion = 1.3` 如果本地存储的字典版本TAGDICVERSION大于等于currentTagDicVersion,是不会更新字典的。
> 如果你想用你自定义的字典，那么要么清除本地localStorage,要么把字典里的版本号和脚本里的版本号都改成大于1.3的相同的两个数。

谢谢开发者老哥的回复 我去捅咕捅咕

**Comment by manakanemu** [comment]
而且字典的地址是不需要改的，字典的地址是根据代码生成器生成的，所以只要你用的是你fork之后的项目的代码生成器，就能自动找到你项目里的字典。

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/114660656-4366df00-9d28-11eb-914a-f269ae185e0b.png)
xie'x谢谢开发者老哥 成功了 原来是 语言|中文 我随便改了下 改成了中文 然后更新版本号就变了 谢谢您

**Comment by manakanemu** [comment]
客气。有意见建议的话欢迎之后继续交流。

**Comment by lhj5426** [comment]
> 客气。有意见建议的话欢迎之后继续交流。

嗯 谢谢
"female:rape":"强奸"
这种 female:rape   female:netorare 格式的支持吗？

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/114662835-eec56300-9d2b-11eb-8d9c-cf6958f1b259.png)
原来是 这种格式 『 f:netorare":"男X女NTR 』爽了 今天晚上把常用的 标签全汉化了 再次感谢 您

**Comment by manakanemu** [comment]
我大概看了下你说的这个情况，因为我原本的标签翻译是针对本子页面的，标签不是"性别:标签"，而是只有标签，所以在标签字典里匹配不到，也就不会翻译。如果你仅仅是想让这部分以”性别:标签“形式展示的标签被翻译，不如直接改脚本。
原始脚本的342行：
```
const tagName = tag.innerText  
tag.innerText = window.reader.tag.dic[tagName] || tagName
````
这一部分是获取标签名称tagName，如果名称包含在tag.dic里，就用tag.dic的翻译代替，如果不包含，则不替换。
你可以在这两句之间插一段，获取tagName后，如果是以性别"性别:"开头，就把这部分去掉，再去tag.dic里面找。不需要一个一个再去翻译。比如:
```
let tagName = tag.innerText  
tagName = tagName.indexOf(':')>-1? tagName.split(':')[1] : tagName
tag.innerText = window.reader.tag.dic[tagName] || tagName
```

**Comment by lhj5426** [comment]
> 我大概看了下你说的这个情况，因为我原本的标签翻译是针对本子页面的，标签不是"性别:标签"，而是只有标签，所以在标签字典里匹配不到，也就不会翻译。如果你仅仅是想让这部分以”性别:标签“形式展示的标签被翻译，不如直接改脚本。
> 原始脚本的342行：
> 
> ```
> const tagName = tag.innerText  
> tag.innerText = window.reader.tag.dic[tagName] || tagName
> ```
> 
> 这一部分是获取标签名称tagName，如果名称包含在tag.dic里，就用tag.dic的翻译代替，如果不包含，则不替换。
> 你可以在这两句之间插一段，获取tagName后，如果是以性别"性别:"开头，就把这部分去掉，再去tag.dic里面找。不需要一个一个再去翻译。比如:
> 
> ```
> let tagName = tag.innerText  
> tagName = tagName.indexOf(':')>-1? tagName.split(':')[1] : tagName
> tag.innerText = window.reader.tag.dic[tagName] || tagName
> ```
奥，谢谢，我去这么弄试试

**Comment by lhj5426** [comment]
其实我是多个脚本混合用在 油猴找到的脚本是可以把本子内部和画廊外搜索框上边的10个分类汉化，但是不能a画廊标签汉化，昨天突然看到画廊部分标签被汉化了，一顿排除法，发现是你都脚本实现的
![DC0D8D5D-0D34-4868-90B4-C2F01DA28224](https://user-images.githubusercontent.com/30548000/114705400-4975b380-9d5a-11eb-91b8-6256881be6aa.png)
![F4B1F73E-2828-4DB3-AB30-D122851DEC64](https://user-images.githubusercontent.com/30548000/114705408-4b3f7700-9d5a-11eb-9dc8-864a9421946e.png)
![DC2624D9-BF90-49C2-9876-C3C4F9A8F807](https://user-images.githubusercontent.com/30548000/114705553-6f9b5380-9d5a-11eb-97aa-e9cf45852cc9.jpeg)

😂现在这样挺像pc版那个 汉化脚本实现的效果
