### ISSUE TITLE
V2 Beta版 reload建议

### ISSUE THREAD

**Issue by Ding-Kyoma** [manakanemu/ExHentaiReader#13]
V2的体验确实更好一点，若能优化一下reload图片的策略就更好了！

目前V2 Beta是手动点一下没有加载出来的图片，有时候看一个本子可能需要点多次，有点不方便。
若能自动reload就好了，例如计算一下加载的时间？超过一定的值后自动重新加载。或者如旧版，能一次性加载未成功显示的图片。

最后感谢一下作者的脚本~

**Comment by manakanemu** [comment]
感谢您的建议。
因为reload图片使用的是备用地址，e站可能会扣除用户更多的观看限额，所以没有做自动reload，之后的改进我会把自动reload做成开关给用户自己选择。目前在对V2的代码重构，做脚本本地化存储的改进，避免每次都从github拉脚本。但是最近有点忙，忙完了我会进行更新。

再次感谢您宝贵的建议。
