### ISSUE TITLE
iPad 下, 底部的翻页按钮过大导致图片不能全屏

### ISSUE THREAD

**Issue by TakChen** [manakanemu/ExHentaiReader#5]
- 测试设备: iPad mini 5
- 测试网页: 任一本子
- 问题描述: 如图, (我这里附上图片是为了给你看效果, 是在 Chrome 上用 iPad 模式模拟出来的,问题是一样的)
  - 希望能调整一下翻页按钮的大小
![image](https://user-images.githubusercontent.com/10719409/73722152-d4274f80-4760-11ea-8f99-58e778696a9b.png)

**Comment by manakanemu** [comment]
👌 这两个问题我找个ipad修复一下

**Comment by manakanemu** [comment]
* 翻页按钮大小问题已经调整了。
* 另一个工具栏一直在底部的问题我的ipad上倒是没复现出来，如果是工具栏过大的话，您可以试着手动指定尺寸。
* 您说的ipad上激活工具栏困难的问题，工具栏的激活是判断惯性滑动，您可以试试滑动屏幕后抬手，让屏幕惯性滑动。

**Comment by TakChen** [comment]
1. 翻页按钮没问题了 👍
2. 工具栏在底部的问题 似乎在 2020-02-05 的 commits 中 以外修复了, 所以我 close 掉了
3. 原来如此, 这激活方式还是得有点技巧的...建议补充在 readme 中
