### ISSUE TITLE
一些ipad pro2018问题反馈

### ISSUE THREAD

**Issue by FolStone** [manakanemu/ExHentaiReader#6]
1下滑在很多时候并不能弹出工具栏，不知道是不是判定过于严格的问题？
2 在safari下，插件版可以正常使用，但框架版自动刷新以后并无效果
3 建议将图片间隔设为蓝色或者网页的灰色，我知道我在看hs漫画……

**Comment by manakanemu** [comment]
* 功能栏的弹出是模仿的safari的地址栏激活方式，判断的是惯性滑动，您可以尝试下滑后松手，靠惯性滑动，这个问题在另一个issue里提到了，我还没来得及写进Readme。
* 框架版目前处于搁浅状态，因为iframe标签和safari的某些机制问题，实现起来颇有困难。不过[issue](https://github.com/manakanemu/ExHentaiReader/issues/2)里也有人提出过用Alook自动执行脚本的方案，可以优化体验。
* 我刚添加了自定义分割线颜色的功能，您可以在新的[代码生成器](https://manakanemu.github.io/ExHentaiReader/)指定分割线颜色。

**Comment by FolStone** [comment]
> * 功能栏的弹出是模仿的safari的地址栏激活方式，判断的是惯性滑动，您可以尝试下滑后松手，靠惯性滑动，这个问题在另一个issue里提到了，我还没来得及写进Readme。
> * 框架版目前处于搁浅状态，因为iframe标签和safari的某些机制问题，实现起来颇有困难。不过[issue](https://github.com/manakanemu/ExHentaiReader/issues/2)里也有人提出过用Alook自动执行脚本的方案，可以优化体验。
> * 我刚添加了自定义分割线颜色的功能，您可以在新的[代码生成器](https://manakanemu.github.io/ExHentaiReader/)指定分割线颜色。

神速添加好评，不过我已经看到并尝试下滑松手，但是大概一半情况无法出现工具栏，另外一部分需要用很小的滑动距离和较短时间才能出现，最后有一小部分可能会出现无论如何滑动也不出现的情况……

**Comment by manakanemu** [comment]
我不太清楚您的具体操作是什么，所以也不太明白您说的不会触发是由什么触发的。
但是可能的原因是，js脚本模拟惯性滑动有一些天生局限，比如惯性滑动的判断依据是**手指离开屏幕时屏幕还在滚动**。但**手指离开屏幕**这个事件在一次完整的滑动中只会触发一次。比如您向下滑了10次，每一次都是不等屏幕停下来就滑动下一次，那么**手指离开屏幕**这个事件只会在第一次触发，后9次都不会触发。所以一旦您第一次惯性滑动是上滑，那么后面不管多少次下滑的惯性滑动都不会激活边栏，这时可以手指轻触屏幕使滑动彻底停止，再下滑。我不知道这个能不能解释您遇到的情况。

而您说的

> 需要用很小的滑动距离和较短时间才能出现

这个是防止误触设计的，后面可能考虑加入自定义灵敏度的功能。
