### ISSUE TITLE
[feature request] 用户能够自行决定是否使用中文化标签

### ISSUE THREAD

**Issue by TakChen** [manakanemu/ExHentaiReader#7]
关于中文化标签, 现在是默认使用的
我本人是不太愿意看中文标签.
希望能有个选项不加载中文标签

**Comment by TakChen** [comment]
哦~ 当我没说, 看了下代码, 有个 translate 的 attribute 可以设置
如果不打算整合到代码生成页那里的话, 还是希望在 README 里面提一下

**Comment by manakanemu** [comment]
刚想回复你，我留了一个自由开关翻译的属性，因为我正在重新写代码生成器的ui，所以暂时就没改。

**Comment by manakanemu** [comment]
加上```s.setAttribute("translate","false");```就关闭翻译了
