### ISSUE TITLE
想了一下，还是希望有能分成两部分的选项

### ISSUE THREAD

**Issue by FolStone** [manakanemu/ExHentaiReader#8]
一般来说点进详细页还是为了确定内容甚至画风，甚至只是看看沙雕网友的评论也是乐趣
现在直接开始加载漫画内容，虽然很方便，但是如果是手误的话，还有可能伤害眼睛……
希望能实现在点进漫画具体页数以后才开始加载后续内容的设置，最好是可以保留详情页的图标翻译

另外之前的自定义分割线怎么没有了……（虽然它确实没效果……

**Comment by TakChen** [comment]
> 希望能实现在点进漫画具体页数以后才开始加载后续内容的设置

建议自己写, 
我自己的需求是: 少于 XXX 页数 自动加载全部内容. 于是我 fork 了一个 改了点代码
还在犹豫要不要拉个 pull request

**Comment by manakanemu** [comment]
最近现实比较忙，没什么时间更新代码，不过这些功能实现倒不是问题，问题是不同习惯的人对应不同需求，从这一点上看很难找到让所有人都百分百满意的加载方式，那就必须考量那种最合适。不过也可以把加载方式写成接口，变成可配置的，过段时间我会试着写一下，不过本来是方便大家使用的东西，逻辑搞得太复杂也不合适。

**Comment by manakanemu** [comment]
>另外之前的自定义分割线怎么没有了……（虽然它确实没效果……  

自定义分割线在代码生成器的```更多配置```里可以修改，不知道你那里是配置问题还是代码出现了bug。
