### ISSUE TITLE
能顺带支持下E-嘛

### ISSUE THREAD

**Issue by lhj5426** [manakanemu/ExHentaiReader#9]
昨天上了下e- 发现好像不支持e- 开发者老哥可以捎带手 支持下e- 嘛

**Comment by manakanemu** [comment]
好，我这两天看一下。

**Comment by manakanemu** [comment]
> 昨天上了下e- 发现好像不支持e- 开发者老哥可以捎带手 支持下e- 嘛

刚添加了对e-的支持，抱歉这两天比较忙，拖了这么久才来更新

**Comment by lhj5426** [comment]
感谢 我去试试
